<?php
/**
 * TL_ROOT/system/modules/rwcards/languages/de/default.php 
 * 
 * Contao extension: rwcards 3.2.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy LoadBrain 
 * License   : LGPL-3.0 
 * Author    : Ralf Weber (loadbrain) 
 * Translator: Ralf Weber (loadbrain) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_listcards_see_all_cards'] = "Zeige alle Karten dieser Kategorie";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_listcards_no_category_published_or_created'] = "Noch keine Kategorien erzeugt oder veröffentlicht!";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_one_category_listcards'] = "Auf eine Karte zur Vollansicht klicken";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_one_category_chosen_category'] = "Gewählte Kategorie";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_one_category_send_this_image'] = "Diese Karte verschicken";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_fillout_cards_please_fill_out'] = "Bitte alle Felder ausfüllen";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_fillout_cards_name_from'] = "Ihr Name";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_fillout_cards_email_from'] = "Ihre E-Mail Adresse";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_fillout_cards_message'] = "Ihre Nachricht";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_fillout_cards_name_to'] = "Name des Empfängers";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_fillout_cards_email_to'] = "E-Mail Adresse des Empfängers";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_fillout_cards_add_receiver'] = "Empfänger hinzufügen";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_fillout_cards_remove_receiver'] = "Empfänger entfernen";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_fillout_cards_back'] = "Zurück";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_fillout_cards_preview_card'] = "Vorschau";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_fillout_cards_send_card'] = "Abschicken";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_preview_card'] = "Voransicht der Karte";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_preview_show_front_card'] = "Vorderseite";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_preview_show_back_card'] = "Rückseite";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_preview_from'] = "Absender:";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_preview_message'] = "Nachricht:";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_preview_to'] = "Empfänger:";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_invalid_code'] = "Falscher Code. Bitte E-Mail nach korrekter URL durchsehen.";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_sucessfully_sent'] = "Ihre E-Card wurde erfolgreich verschickt";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_view_your_card'] = "Persönliche E-Card für";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_congratulations'] = "Herzlichen Glückwunsch!";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_view_your_card_hint'] = "Klicken Sie auf \"Zeige hintere Ansicht\" um zu antworten!";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_congatulations_hint'] = "Sie werden eine Bestätigungs E-Mail bekommen, sobald der Empfänger die Karte gelesen hat.";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_show_front_card'] = "Zeige vordere Ansicht";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_show_back_card'] = "Zeige hintere Ansicht";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_from'] = "Von:";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_name_from'] = "Name";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_message'] = "Nachricht";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_to'] = "An:";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_name_to'] = "Name des Empfämgers";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_reply'] = "jetzt antworten";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_subject'] = "Sie haben eine ECard erhalten! Absender: ";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_greeting'] = "Hallo";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_msg_attachement_1'] = "hat Ihnen eine ECard geschickt.";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_msg_attachement_2'] = "Im Attachement das Bild der ECard.";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_msg_attachement_3'] = "Hier seine Nachricht:";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_msg_separator'] = "----------------------------------------------------------------------";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_msg_copyright'] = "RWCards - Copyright Ralf Weber / LoadBrain - http://www.loadbrain.de/";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_msg_part_1'] = "hat Ihnen eine ECard geschickt.";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_msg_part_2'] = "Klicken Sie auf den folgenden Link um Ihre ECard anzusehen:";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_read_subject'] = "Ihre ECard wurde gelesen!";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_read_msg_1'] = "hat Ihre Karte am";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_read_msg_2'] = "gelesen.";
$GLOBALS['TL_LANG']['tl_rwcards']['rwcards_sendcard_read_msg_3'] = "Weiterhin viel Spass mit RWCards!";
 
?>
