<?php
/**
 * TL_ROOT/system/modules/rwcards/languages/de/tl_module.php 
 * 
 * Contao extension: rwcards 1.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy 2011 Ralf Weber - LoadBrain 
 * License   : Creative Commons Attribution 2.0 
 * Author    : Ralf Weber (loadbrain) 
 * Translator: Ralf Weber (loadbrain) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['rwcards_view_categories']['0'] = "Kategorienübersicht anzeigen oder direkt alle Karten (nur eine Kategorie existiert)?";
$GLOBALS['TL_LANG']['tl_module']['rwcards_view_categories']['1'] = "Kategorienübersicht anzeigen oder direkt alle Karten";
$GLOBALS['TL_LANG']['tl_module']['rwcards_view_categories']['options']['0'] = "Kategorienübersicht anzeigen";
$GLOBALS['TL_LANG']['tl_module']['rwcards_view_categories']['options']['1'] = "Direkt alle Karten aus einer Kategorie (nur eine Kategorie darf existieren)";
$GLOBALS['TL_LANG']['tl_module']['rwcards_cards_per_row']['0'] = "Wieviel Karten pro Reihe?";
$GLOBALS['TL_LANG']['tl_module']['rwcards_cards_per_row']['1'] = "Wieviele Karten sollen in einer Reihe auf der Seite angezeigt werden?";
$GLOBALS['TL_LANG']['tl_module']['rwcards_rows_per_page']['0'] = "Wieviel Reihen pro Seite?";
$GLOBALS['TL_LANG']['tl_module']['rwcards_rows_per_page']['1'] = "Wieviele Reihen soll auf einer Seite angezeigt werden?.";
$GLOBALS['TL_LANG']['tl_module']['rwcards_keep_cards']['0'] = "Wieviel Tage sollen Karten aufgehoben werden?";
$GLOBALS['TL_LANG']['tl_module']['rwcards_keep_cards']['1'] = "Wieviel Tage sollen Karten aufgehoben werden? 0 = nie löschen";
$GLOBALS['TL_LANG']['tl_module']['thumb_box_width']['0'] = "Wie breit soll die Box der Karten Voransicht sein?";
$GLOBALS['TL_LANG']['tl_module']['thumb_box_width']['1'] = "Wie breit soll die Box der Karten Voransicht sein?";
$GLOBALS['TL_LANG']['tl_module']['thumb_box_height']['0'] = "Wie hoch soll die Box der Karten Voransicht sein";
$GLOBALS['TL_LANG']['tl_module']['thumb_box_height']['1'] = "Wie hoch soll die Box der Karten Voransicht sein";
$GLOBALS['TL_LANG']['tl_module']['rwcards_thumbnail_width']['0'] = "Wie breit sollen die thumbnails der Karten sein?";
$GLOBALS['TL_LANG']['tl_module']['rwcards_thumbnail_width']['1'] = "Wie breit sollen die thumbnails der Karten sein?";
$GLOBALS['TL_LANG']['tl_module']['rwcards_thumbnail_height']['0'] = "Wie hoch soll die thumbnails  der Karten sein?";
$GLOBALS['TL_LANG']['tl_module']['rwcards_thumbnail_height']['1'] = "Wie hoch soll die thumbnails  der Karten sein?";
$GLOBALS['TL_LANG']['tl_module']['rwcards_per_attachement']['0'] = "Bild der Karte als Attachement der Email schicken?";
$GLOBALS['TL_LANG']['tl_module']['rwcards_per_attachement']['1'] = "Soll das Bild der E-Card als Attachement mit der E-Mail geschickt werden oder ein Link zur Seite um die Karte aufzurufen (empfohlen)";
$GLOBALS['TL_LANG']['tl_module']['0'] = "Nein, URL zur Karte in der E-Mail schicken";
$GLOBALS['TL_LANG']['tl_module']['1'] = "Ja, als Attachement verschicken";
 
?>
