<?php
/**
 * TL_ROOT/system/modules/rwcards/languages/de/tl_rwcards.php 
 * 
 * Contao extension: rwcards 1.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy 2011 Ralf Weber - LoadBrain 
 * License   : Creative Commons Attribution 2.0 
 * Author    : Ralf Weber (loadbrain) 
 * Translator: Ralf Weber (loadbrain) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_rwcards']['autor']['0'] = "Autor";
$GLOBALS['TL_LANG']['tl_rwcards']['autor']['1'] = "Der Name des Autors";
$GLOBALS['TL_LANG']['tl_rwcards']['autor_legend'] = "Geben Sie Informationen zum Autor ein";
$GLOBALS['TL_LANG']['tl_rwcards']['email']['0'] = "E-Mail Adresse des Autors";
$GLOBALS['TL_LANG']['tl_rwcards']['email']['1'] = "E-Mail Adresse des Autors";
$GLOBALS['TL_LANG']['tl_rwcards']['picture_legend'] = "Wählen Sie ein Bild aus";
$GLOBALS['TL_LANG']['tl_rwcards']['emailFrom']['0'] = "E-Mail Adresse des Absenders";
$GLOBALS['TL_LANG']['tl_rwcards']['emailFrom']['1'] = "E-Mail Adresse des Absenders";
$GLOBALS['TL_LANG']['tl_rwcards']['picture']['0'] = "Bild";
$GLOBALS['TL_LANG']['tl_rwcards']['picture']['1'] = "Wählen Sie ein Bild aus dem Dateisystem aus";
$GLOBALS['TL_LANG']['tl_rwcards']['description']['0'] = "Beschreibung";
$GLOBALS['TL_LANG']['tl_rwcards']['description']['1'] = "Hier können Sie eine Beschreibung für Ihre Karte eingeben";
$GLOBALS['TL_LANG']['tl_rwcards']['description_legend'] = "Beschreibung";
$GLOBALS['TL_LANG']['tl_rwcards']['published']['0'] = "Karte verföffentlichen";
$GLOBALS['TL_LANG']['tl_rwcards']['published']['1'] = "Nur veröffentlichte Karten werden angezeigt!";
$GLOBALS['TL_LANG']['tl_rwcards']['published_legend'] = "Karte verföffentlichen";
$GLOBALS['TL_LANG']['tl_rwcards']['size']['0'] = "Bildgröße";
$GLOBALS['TL_LANG']['tl_rwcards']['size']['1'] = "Geben Sie die Bildgröße für die Thumbnailansicht ein";
 
?>
