<?php
/**
 * TL_ROOT/system/modules/rwcards/languages/de/tl_rwcards_category.php 
 * 
 * Contao extension: rwcards 3.2.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy LoadBrain 
 * License   : LGPL-3.0 
 * Author    : Ralf Weber (loadbrain) 
 * Translator: Ralf Weber (loadbrain) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_rwcards_category']['category_kategorien_name']['0'] = "Kategorie";
$GLOBALS['TL_LANG']['tl_rwcards_category']['category_kategorien_name']['1'] = "Geben Sie eien Namen für die Kategorie an";
$GLOBALS['TL_LANG']['tl_rwcards_category']['category_kategorien_name_legend'] = "Geben Sie eine Kategorie ein";
$GLOBALS['TL_LANG']['tl_rwcards_category']['category_description']['0'] = "Hier können Sie Ihre Kategorie beschreiben";
$GLOBALS['TL_LANG']['tl_rwcards_category']['category_description']['1'] = "Hier können Sie Ihre Kategorie beschreiben";
$GLOBALS['TL_LANG']['tl_rwcards_category']['published']['0'] = "Veröffentlichen";
$GLOBALS['TL_LANG']['tl_rwcards_category']['published']['1'] = "Veröffentlichen";
$GLOBALS['TL_LANG']['tl_rwcards_category']['published_legend']['0'] = "Veröffentlichen";
$GLOBALS['TL_LANG']['tl_rwcards_category']['published_legend']['1'] = "Veröffentlichen";
$GLOBALS['TL_LANG']['tl_rwcards_category']['new']['0'] = "Neue Kategorie anlegen";
$GLOBALS['TL_LANG']['tl_rwcards_category']['new']['1'] = "Eine neue Kategorie anlegen";
$GLOBALS['TL_LANG']['tl_rwcards']['new']['0'] = "Neue Karte anlegen";
$GLOBALS['TL_LANG']['tl_rwcards']['new']['1'] = "Eine neue Karte anlegen";
 
?>
