<?php
/**
 * TL_ROOT/system/modules/rwcards/languages/de/tl_rwcardsdata.php 
 * 
 * Contao extension: rwcards 3.2.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy LoadBrain 
 * License   : LGPL-3.0 
 * Author    : Ralf Weber (loadbrain) 
 * Translator: Ralf Weber (loadbrain) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_rwcardsdata']['nameTo']['0'] = "Empfänger";
$GLOBALS['TL_LANG']['tl_rwcardsdata']['nameTo']['1'] = "Empfänger";
$GLOBALS['TL_LANG']['tl_rwcardsdata']['emailTo']['0'] = "E-Mail Adresse des Empfängers";
$GLOBALS['TL_LANG']['tl_rwcardsdata']['emailTo']['1'] = "E-Mail Adresse des Empfängers";
$GLOBALS['TL_LANG']['tl_rwcardsdata']['nameFrom']['0'] = "Empfänger";
$GLOBALS['TL_LANG']['tl_rwcardsdata']['emailFrom']['0'] = "E-Mail Adresse des Absenders";
$GLOBALS['TL_LANG']['tl_rwcardsdata']['emailFrom']['1'] = "E-Mail Adresse des Absenders";
$GLOBALS['TL_LANG']['tl_rwcardsdata']['picture']['0'] = "Bild";
$GLOBALS['TL_LANG']['tl_rwcardsdata']['picture']['1'] = "Bild";
$GLOBALS['TL_LANG']['tl_rwcardsdata']['message']['0'] = "Nachricht";
$GLOBALS['TL_LANG']['tl_rwcardsdata']['message']['1'] = "Nachricht";
$GLOBALS['TL_LANG']['tl_rwcardsdata']['writtenOn']['0'] = "Geschrieben am";
$GLOBALS['TL_LANG']['tl_rwcardsdata']['writtenOn']['1'] = "Geschrieben am";
$GLOBALS['TL_LANG']['tl_rwcardsdata']['readOn']['0'] = "Gelesen am";
$GLOBALS['TL_LANG']['tl_rwcardsdata']['readOn']['1'] = "Gelesen am";
$GLOBALS['TL_LANG']['tl_rwcardsdata']['cardSent']['0'] = "Gesendet";
$GLOBALS['TL_LANG']['tl_rwcardsdata']['cardRead']['0'] = "Gelesen";
 
?>
